swagger: "2.0"
info:
  title: "My first API"
  version: "1.0"
basePath: /v1.0
paths:
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
    post:
      parameters:
        - name: item
          in: body
          schema:
            $ref: '#/definitions/Item'
      responses:
        '200':
          description: 'Created a new Item'
          schema:
            $ref: '#/definitions/Item'
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64app
      name: { type: string }